apiVersion: v1
kind: Secret
metadata:
  name: gearup-secret
  namespace: gearup
type: Opaque
stringData:
  POSTGRES_DB: GearUp
  POSTGRES_USER: gearup
  POSTGRES_PASSWORD: GearUp_Strong!Pass123
  Jwt__Key: gearup-local-development-key-change-me
  Seed__AdminPassword: GearUp@123
  ConnectionStrings__GearUpDatabase: Host=gearup-postgres;Port=5432;Database=GearUp;Username=gearup;Password=GearUp_Strong!Pass123
