apiVersion: v1
kind: Secret
metadata:
  name: gearup-secret
  namespace: gearup
type: Opaque
stringData:
  POSTGRES_DB: GearUp
  POSTGRES_USER: gearup
  POSTGRES_PASSWORD: GearUp_Strong!Pass123
  Jwt__Key: 4f5dc4919019430689e415ff2ac6037e9765385b2bcf47758dabd747e08b52b4
  ConnectionStrings__GearUpDatabase: Host=gearup-postgres;Port=5432;Database=GearUp;Username=gearup;Password=GearUp_Strong!Pass123