// <auto-generated />
using System;
using GearUp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GearUp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GearUpDbContext))]
    [Migration("20260930003943_Fase3ConsistenciaEPerformance")]
    partial class Fase3ConsistenciaEPerformance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GearUp.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .IsUnicode(false)
                        .HasColumnType("character varying(254)");

                    b.Property<DateTimeOffset?>("ExcluidoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("character varying(11)");

                    b.HasKey("Id");

                    b.HasIndex("Documento")
                        .IsUnique()
                        .HasDatabaseName("UX_Clientes_Documento");

                    b.ToTable("Clientes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Clientes_Documento_Tamanho", "char_length(\"Documento\") IN (11, 14)");
                        });
                });

            modelBuilder.Entity("GearUp.Domain.Entities.Estoque", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("QuantidadeDisponivel")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("EstoqueItens", null, t =>
                        {
                            t.HasCheckConstraint("CK_EstoqueItens_PrecoUnitario", "\"PrecoUnitario\" >= 0");

                            t.HasCheckConstraint("CK_EstoqueItens_QuantidadeDisponivel", "\"QuantidadeDisponivel\" >= 0");
                        });
                });

            modelBuilder.Entity("GearUp.Domain.Entities.HistoricoOrdemServico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("OrdemServicoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("CriadoEm");

                    b.HasIndex("OrdemServicoId", "CriadoEm");

                    b.ToTable("HistoricoOrdensServico", (string)null);
                });

            modelBuilder.Entity("GearUp.Domain.Entities.ItemOrcamento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("EstoqueItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrcamentoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EstoqueItemId");

                    b.HasIndex("OrcamentoId");

                    b.ToTable("ItensOrcamento", null, t =>
                        {
                            t.HasCheckConstraint("CK_ItensOrcamento_Quantidade", "\"Quantidade\" > 0");

                            t.HasCheckConstraint("CK_ItensOrcamento_ValorUnitario", "\"ValorUnitario\" >= 0");
                        });
                });

            modelBuilder.Entity("GearUp.Domain.Entities.MovimentacaoEstoque", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EstoqueItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("OrdemServicoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CriadoEm");

                    b.HasIndex("EstoqueItemId");

                    b.HasIndex("OrdemServicoId");

                    b.ToTable("MovimentacoesEstoque", null, t =>
                        {
                            t.HasCheckConstraint("CK_MovimentacoesEstoque_Quantidade", "\"Quantidade\" > 0");
                        });
                });

            modelBuilder.Entity("GearUp.Domain.Entities.Notificacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Destinatario")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LidaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("OrdemServicoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrdemServicoId");

                    b.HasIndex("ClienteId", "CriadaEm");

                    b.HasIndex("Destinatario", "LidaEm");

                    b.ToTable("Notificacoes", (string)null);
                });

            modelBuilder.Entity("GearUp.Domain.Entities.Orcamento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DecididoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrdemServicoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Versao")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrdemServicoId", "Versao")
                        .IsUnique();

                    b.ToTable("Orcamentos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Orcamentos_Versao", "\"Versao\" > 0");
                        });
                });

            modelBuilder.Entity("GearUp.Domain.Entities.OrdemServico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Diagnostico")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset?>("FinalizadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("IniciadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MecanicoId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("Prazo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Prioridade")
                        .HasColumnType("integer");

                    b.Property<string>("SolicitacaoInicial")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("VeiculoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MecanicoId");

                    b.HasIndex("VeiculoId");

                    b.HasIndex("ClienteId", "CriadaEm")
                        .IsDescending(false, true);

                    b.HasIndex("Status", "Prioridade", "CriadaEm");

                    b.ToTable("OrdensServico", (string)null);
                });

            modelBuilder.Entity("GearUp.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("NomeUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("GearUp.Domain.Entities.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("character varying(7)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("Veiculos", (string)null);
                });

            modelBuilder.Entity("GearUp.Domain.Entities.HistoricoOrdemServico", b =>
                {
                    b.HasOne("GearUp.Domain.Entities.OrdemServico", null)
                        .WithMany("Historico")
                        .HasForeignKey("OrdemServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GearUp.Domain.Entities.ItemOrcamento", b =>
                {
                    b.HasOne("GearUp.Domain.Entities.Orcamento", null)
                        .WithMany("Itens")
                        .HasForeignKey("OrcamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GearUp.Domain.Entities.MovimentacaoEstoque", b =>
                {
                    b.HasOne("GearUp.Domain.Entities.Estoque", null)
                        .WithMany("Movimentacoes")
                        .HasForeignKey("EstoqueItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GearUp.Domain.Entities.Notificacao", b =>
                {
                    b.HasOne("GearUp.Domain.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GearUp.Domain.Entities.OrdemServico", null)
                        .WithMany()
                        .HasForeignKey("OrdemServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GearUp.Domain.Entities.Orcamento", b =>
                {
                    b.HasOne("GearUp.Domain.Entities.OrdemServico", null)
                        .WithMany()
                        .HasForeignKey("OrdemServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GearUp.Domain.Entities.OrdemServico", b =>
                {
                    b.HasOne("GearUp.Domain.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GearUp.Domain.Entities.Veiculo", null)
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GearUp.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("GearUp.Domain.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GearUp.Domain.Entities.Veiculo", b =>
                {
                    b.HasOne("GearUp.Domain.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GearUp.Domain.Entities.Estoque", b =>
                {
                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("GearUp.Domain.Entities.Orcamento", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("GearUp.Domain.Entities.OrdemServico", b =>
                {
                    b.Navigation("Historico");
                });
#pragma warning restore 612, 618
        }
    }
}
