apiVersion: v1
kind: Service
metadata:
  name: gearup-api
  namespace: gearup
  labels:
    app: gearup-api
spec:
  type: LoadBalancer
  selector:
    app: gearup-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
